import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/components/providers/AuthProvider";
import { QueryProvider } from "@/components/providers/QueryProvider";
import { Navbar } from "@/components/Navbar";
import { cn } from "@/lib/utils/cn";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("bg-background-500 relative w-full", poppins.className)}
      >
        <AuthProvider>
          <QueryProvider>
            <Navbar />
            {children}
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
